name: todo_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  bloc: ^8.1.1
  conditional_builder_null_safety: ^0.0.6
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_slidable: ^3.0.1
  intl: null
  sqflite: null

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
